-- PPIQ RULE 2 EMPTY-START PROOF
--
-- GENERATED by Apply-PpiqRule2EmptyStartProof.ps1 from
-- Backend/database/acceptance/rule2_prefill_allowlist.txt.
-- EDIT THE ALLOWLIST, NOT THIS FILE.
--
-- One query. One number. It must be 0 on a freshly migrated database with no
-- seed applied. Any table not on the allowlist is counted, so a table added
-- later is plant data by default and this proof goes red until it is
-- classified deliberately.
--
-- Usage:
--   psql -d ppiq_acceptance_empty -v ON_ERROR_STOP=1 -f rule2_proof.sql

WITH candidate AS (
    SELECT c.oid, n.nspname, c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relkind = 'r'
      AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
      AND c.relname NOT IN ('industry_templates', 'material_unit_type_definitions', 'dashboard_definitions', 'dashboard_widget_definitions', 'kpi_definitions', '__EFMigrationsHistory', 'schema_migrations')
),
counted AS (
    SELECT
        candidate.nspname,
        candidate.relname,
        (xpath(
            '/row/c/text()',
            query_to_xml(
                format('SELECT count(*) AS c FROM %I.%I', candidate.nspname, candidate.relname),
                false, true, ''
            )
        ))[1]::text::bigint AS row_count
    FROM candidate
)
SELECT
    coalesce(sum(row_count), 0) AS non_empty_rows_outside_allowlist,
    coalesce(count(*) FILTER (WHERE row_count > 0), 0) AS offending_tables
FROM counted;

-- Diagnostic companion: WHICH tables hold rows. Run this only when the number
-- above is not zero.
--
-- WITH candidate AS (...same as above...), counted AS (...same...)
-- SELECT nspname, relname, row_count FROM counted WHERE row_count > 0 ORDER BY row_count DESC;