#!/usr/bin/env python3
"""
PlantProcess IQ — Phase 1 Golden Demo Data Generator

Tasks:
  PPIQ-DEMO-001
  PPIQ-DEMO-009

Generates:
  Backend/database/scripts/112_phase1_golden_demo_data.sql

Target source-shaped story:
  - MeltShop PostgreSQL-shaped source
  - Caster Oracle-shaped source
  - HSM Oracle-shaped source
  - PKL MSSQL-shaped source
  - Downtime + Parsytec MySQL-shaped source

No third-party Python packages required.
"""

from __future__ import annotations

import argparse
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_num(value: float | int | None, decimals: int = 3) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return f"{value:.{decimals}f}"


def sql_ts(value: datetime | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S+00") + "'"

def injected_quality_correlation(actual_fdt_c: float, actual_ct_c: float, thickness_mm: float) -> float:
    """
    PPIQ-DEMO-010:
    Inject a realistic but not deterministic correlation signal.

    Purpose:
    - Makes rule-based/correlation engines discover a suspected contributor.
    - Does not make defects perfectly predictable.
    - Keeps demo honest: evidence pattern, not guaranteed root cause.
    """
    risk = 0.035

    if actual_fdt_c > 910:
        risk += 0.055

    if actual_ct_c < 560:
        risk += 0.045

    if thickness_mm < 2.2:
        risk += 0.025

    return min(risk, 0.28)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--heats", type=int, default=630)
    parser.add_argument("--slabs-per-heat", type=int, default=9)
    parser.add_argument("--start", default="2026-04-01T00:00:00+00:00")
    parser.add_argument(
        "--out",
        default="Backend/database/scripts/112_phase1_golden_demo_data.sql",
    )
    parser.add_argument("--seed", type=int, default=20260525)
    args = parser.parse_args()

    random.seed(args.seed)

    start = datetime.fromisoformat(args.start)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    grades = ["DX51D", "S235JR", "S355MC", "IF-LOW-C", "HSLA-420", "DP600"]
    furnaces = ["EAF-01", "EAF-02"]
    lfs = ["LF-01", "LF-02"]
    casters = ["CCM-01", "CCM-02"]
    hsm_lines = ["HSM-01"]
    pkl_lines = ["PKL-01", "PKL-02"]
    defect_codes = [
        ("SCALE", "Scale", "surface"),
        ("SCRATCH", "Scratch", "surface"),
        ("EDGE_CRACK", "Edge crack", "edge"),
        ("ROLLED_IN", "Rolled-in scale", "surface"),
        ("PINHOLE", "Pinhole", "surface"),
        ("WAVINESS", "Waviness", "shape"),
    ]
    downtime_reasons = [
        ("MECH_ROLL_CHANGE", "Mechanical roll change", "planned"),
        ("SENSOR_FAULT", "Sensor fault", "unplanned"),
        ("HYDRAULIC_ALARM", "Hydraulic alarm", "unplanned"),
        ("QUALITY_HOLD", "Quality hold", "quality"),
        ("ENTRY_DELAY", "Entry section delay", "logistics"),
    ]

    heat_count = args.heats
    slabs_per_heat = args.slabs_per_heat
    coil_count = heat_count * slabs_per_heat

    lines: list[str] = []
    lines.append("-- PlantProcess IQ Phase 1 Golden Demo Data")
    lines.append("-- Generated by tools/phase1/generate_phase1_golden_demo_data.py")
    lines.append("SET client_min_messages TO WARNING;")
    lines.append("SET TIME ZONE 'UTC';")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("TRUNCATE TABLE")
    lines.append("  src_inspection_mysql_shape.downtime_events,")
    lines.append("  src_inspection_mysql_shape.parsytec_surface_defects,")
    lines.append("  src_pkl_mssql_shape.qa_lab_results,")
    lines.append("  src_pkl_mssql_shape.pickle_orders,")
    lines.append("  src_hsm_oracle_shape.hsm_pass_measurements,")
    lines.append("  src_hsm_oracle_shape.hsm_coils,")
    lines.append("  src_caster_oracle_shape.cast_pieces,")
    lines.append("  src_caster_oracle_shape.cast_sequence,")
    lines.append("  src_meltshop_pg.lf_treatment,")
    lines.append("  src_meltshop_pg.heats")
    lines.append("RESTART IDENTITY;")
    lines.append("")

    sequence_counter = 1
    coil_counter = 1
    pass_rows = 0
    defect_rows = 0
    lab_rows = 0
    downtime_rows = 0

    for heat_index in range(1, heat_count + 1):
        heat_no = f"H{start.year}{heat_index:05d}"
        grade = random.choice(grades)
        furnace = random.choice(furnaces)
        route = "EAF-LF-CCM-HSM-PKL"
        tap_start = start + timedelta(minutes=70 * (heat_index - 1))
        tap_end = tap_start + timedelta(minutes=random.randint(42, 58))
        actual_temp = random.normalvariate(1648, 22)

        lines.append(
            "INSERT INTO src_meltshop_pg.heats "
            "(heat_no, plant_code, furnace_code, steel_grade, route_code, tap_start_utc, tap_end_utc, "
            "heat_weight_ton, target_temp_c, actual_temp_c, oxygen_nm3, power_kwh, carbon_pct, manganese_pct, silicon_pct, source_updated_at_utc) "
            f"VALUES ({sql_text(heat_no)}, 'DEMO_PLANT', {sql_text(furnace)}, {sql_text(grade)}, {sql_text(route)}, "
            f"{sql_ts(tap_start)}, {sql_ts(tap_end)}, "
            f"{sql_num(random.uniform(145, 175))}, 1650.00, {sql_num(actual_temp, 2)}, "
            f"{sql_num(random.uniform(3200, 5100))}, {sql_num(random.uniform(69000, 85000))}, "
            f"{sql_num(random.uniform(0.025, 0.18), 5)}, {sql_num(random.uniform(0.25, 1.6), 5)}, {sql_num(random.uniform(0.01, 0.32), 5)}, "
            f"{sql_ts(tap_end + timedelta(minutes=2))});"
        )

        lf_start = tap_end + timedelta(minutes=random.randint(8, 16))
        lf_end = lf_start + timedelta(minutes=random.randint(28, 48))
        lines.append(
            "INSERT INTO src_meltshop_pg.lf_treatment "
            "(heat_no, lf_code, treatment_start_utc, treatment_end_utc, argon_flow_nm3, calcium_wire_m, final_temp_c, sample_result_code, source_updated_at_utc) "
            f"VALUES ({sql_text(heat_no)}, {sql_text(random.choice(lfs))}, {sql_ts(lf_start)}, {sql_ts(lf_end)}, "
            f"{sql_num(random.uniform(120, 280))}, {sql_num(random.uniform(20, 110))}, {sql_num(random.normalvariate(1610, 16), 2)}, "
            f"{sql_text('OK' if random.random() > 0.07 else 'CHECK')}, {sql_ts(lf_end + timedelta(minutes=2))});"
        )

        sequence_no = f"SEQ{sequence_counter:05d}"
        sequence_counter += 1
        caster = random.choice(casters)
        seq_start = lf_end + timedelta(minutes=random.randint(15, 30))
        seq_end = seq_start + timedelta(minutes=slabs_per_heat * random.randint(6, 9))

        lines.append(
            "INSERT INTO src_caster_oracle_shape.cast_sequence "
            "(sequence_no, caster_id, tundish_no, start_time, end_time, planned_grade, actual_grade, sequence_status, last_update_ts) "
            f"VALUES ({sql_text(sequence_no)}, {sql_text(caster)}, {sql_text('TD-' + str(random.randint(1, 6)))}, "
            f"{sql_ts(seq_start)}, {sql_ts(seq_end)}, {sql_text(grade)}, {sql_text(grade)}, 'Completed', {sql_ts(seq_end)});"
        )

        for slab_index in range(1, slabs_per_heat + 1):
            piece_id = f"SLB{heat_index:05d}{slab_index:02d}"
            coil_id = f"C{coil_counter:07d}"
            coil_counter += 1

            cut_time = seq_start + timedelta(minutes=slab_index * random.randint(6, 9))
            width = random.choice([950, 1050, 1250, 1450, 1550]) + random.uniform(-7, 7)
            thickness = random.choice([220, 230, 250]) + random.uniform(-2, 2)
            length = random.uniform(8500, 11800)

            casting_speed = random.normalvariate(1.35, 0.12)
            mould_level = random.normalvariate(0.0, 2.5)
            superheat = random.normalvariate(24, 8)

            lines.append(
                "INSERT INTO src_caster_oracle_shape.cast_pieces "
                "(piece_id, heat_no, sequence_no, caster_id, strand_no, slab_no, cut_time, width_mm, thickness_mm, length_mm, weight_kg, "
                "mould_level_avg, casting_speed_avg, superheat_c, last_update_ts) "
                f"VALUES ({sql_text(piece_id)}, {sql_text(heat_no)}, {sql_text(sequence_no)}, {sql_text(caster)}, "
                f"{random.randint(1, 2)}, {slab_index}, {sql_ts(cut_time)}, {sql_num(width, 2)}, {sql_num(thickness, 2)}, "
                f"{sql_num(length, 2)}, {sql_num(random.uniform(18000, 31000))}, {sql_num(mould_level, 4)}, "
                f"{sql_num(casting_speed, 4)}, {sql_num(superheat, 4)}, {sql_ts(cut_time + timedelta(minutes=2))});"
            )

            rolling_start = cut_time + timedelta(hours=random.randint(3, 30), minutes=random.randint(0, 59))
            rolling_end = rolling_start + timedelta(minutes=random.randint(8, 18))
            actual_fdt = random.normalvariate(875, 22)
            actual_ct = random.normalvariate(610, 28)
            actual_thickness = random.choice([1.5, 2.0, 2.5, 3.0, 4.0]) + random.uniform(-0.08, 0.08)

            lines.append(
                "INSERT INTO src_hsm_oracle_shape.hsm_coils "
                "(coil_id, input_piece_id, heat_no, mill_line, rolling_start_time, rolling_end_time, target_fdt_c, actual_fdt_c, "
                "target_ct_c, actual_ct_c, target_thickness_mm, actual_thickness_mm, target_width_mm, actual_width_mm, coil_weight_kg, last_update_ts) "
                f"VALUES ({sql_text(coil_id)}, {sql_text(piece_id)}, {sql_text(heat_no)}, {sql_text(random.choice(hsm_lines))}, "
                f"{sql_ts(rolling_start)}, {sql_ts(rolling_end)}, 875.00, {sql_num(actual_fdt, 2)}, 610.00, {sql_num(actual_ct, 2)}, "
                f"{sql_num(actual_thickness, 4)}, {sql_num(actual_thickness, 4)}, {sql_num(width, 2)}, {sql_num(width + random.uniform(-3, 3), 2)}, "
                f"{sql_num(random.uniform(12500, 28500))}, {sql_ts(rolling_end)});"
            )

            for stand_no in range(1, 8):
                sample_time = rolling_start + timedelta(minutes=stand_no)
                lines.append(
                    "INSERT INTO src_hsm_oracle_shape.hsm_pass_measurements "
                    "(coil_id, stand_no, sample_time, rolling_force_kn, roll_gap_mm, speed_mps, temperature_c, last_update_ts) "
                    f"VALUES ({sql_text(coil_id)}, {stand_no}, {sql_ts(sample_time)}, "
                    f"{sql_num(random.uniform(8200, 24500))}, {sql_num(random.uniform(0.6, 6.0), 5)}, "
                    f"{sql_num(random.uniform(4.0, 18.5), 5)}, {sql_num(actual_fdt + random.uniform(-35, 35), 2)}, {sql_ts(sample_time)});"
                )
                pass_rows += 1

            pkl_start = rolling_end + timedelta(hours=random.randint(4, 72))
            pkl_end = pkl_start + timedelta(minutes=random.randint(20, 55))
            qa_decision = random.choices(["Accepted", "Downgraded", "Hold", "Rejected"], weights=[88, 7, 4, 1])[0]

            lines.append(
                "INSERT INTO src_pkl_mssql_shape.pickle_orders "
                "(order_id, coil_id, line_id, customer_code, entry_time_utc, exit_time_utc, acid_concentration_pct, bath_temperature_c, "
                "line_speed_mpm, inspection_result, qa_decision, modified_at_utc) "
                f"VALUES ({sql_text('PKL-' + coil_id)}, {sql_text(coil_id)}, {sql_text(random.choice(pkl_lines))}, "
                f"{sql_text('CUST-' + str(random.randint(100, 999)))}, {sql_ts(pkl_start)}, {sql_ts(pkl_end)}, "
                f"{sql_num(random.uniform(5.5, 11.5), 4)}, {sql_num(random.uniform(72, 92), 2)}, {sql_num(random.uniform(80, 240), 3)}, "
                f"{sql_text('OK' if qa_decision == 'Accepted' else 'CHECK')}, {sql_text(qa_decision)}, {sql_ts(pkl_end)});"
            )

            for test_code in ["THK", "WIDTH", "ROUGHNESS"]:
                lines.append(
                    "INSERT INTO src_pkl_mssql_shape.qa_lab_results "
                    "(coil_id, sample_time_utc, test_code, measured_value, unit_code, result_status, modified_at_utc) "
                    f"VALUES ({sql_text(coil_id)}, {sql_ts(pkl_end + timedelta(minutes=5))}, {sql_text(test_code)}, "
                    f"{sql_num(random.uniform(1.0, 1600.0), 6)}, {sql_text('mm' if test_code != 'ROUGHNESS' else 'um')}, "
                    f"{sql_text('OK' if random.random() > 0.04 else 'CHECK')}, {sql_ts(pkl_end + timedelta(minutes=6))});"
                )
                lab_rows += 1

            defect_probability = 0.16
            if actual_fdt < 835 or actual_ct > 670 or abs(mould_level) > 4.5:
                defect_probability = 0.38

            if random.random() < defect_probability:
                for _ in range(random.randint(1, 3)):
                    code, name, defect_class = random.choice(defect_codes)
                    defect_time = rolling_end + timedelta(minutes=random.randint(2, 20))
                    pos_start = random.uniform(0, 800)
                    pos_end = pos_start + random.uniform(0.5, 25)

                    lines.append(
                        "INSERT INTO src_inspection_mysql_shape.parsytec_surface_defects "
                        "(coil_id, inspection_device, defect_code, defect_name, defect_class, defect_severity, side_code, "
                        "position_start_m, position_end_m, width_position_mm, confidence_pct, event_time_utc, updated_at_utc) "
                        f"VALUES ({sql_text(coil_id)}, 'PARSYTEC-01', {sql_text(code)}, {sql_text(name)}, {sql_text(defect_class)}, "
                        f"{sql_text(random.choice(['low', 'medium', 'high']))}, {sql_text(random.choice(['TOP', 'BOT']))}, "
                        f"{sql_num(pos_start, 3)}, {sql_num(pos_end, 3)}, {sql_num(random.uniform(50, 1450), 3)}, "
                        f"{sql_num(random.uniform(70, 99), 4)}, {sql_ts(defect_time)}, {sql_ts(defect_time)});"
                    )
                    defect_rows += 1

    total_hours = int((heat_count * 70) / 60)
    for i in range(max(120, heat_count // 3)):
        event_start = start + timedelta(hours=random.randint(0, max(1, total_hours)), minutes=random.randint(0, 59))
        duration = random.randint(180, 5400)
        reason_code, reason_text, category = random.choice(downtime_reasons)
        equipment = random.choice(["EAF-01", "EAF-02", "LF-01", "LF-02", "CCM-01", "CCM-02", "HSM-01", "PKL-01", "PKL-02"])

        lines.append(
            "INSERT INTO src_inspection_mysql_shape.downtime_events "
            "(equipment_code, source_line, reason_code, reason_text, downtime_category, start_time_utc, end_time_utc, duration_seconds, updated_at_utc) "
            f"VALUES ({sql_text(equipment)}, {sql_text(equipment.split('-')[0])}, {sql_text(reason_code)}, {sql_text(reason_text)}, "
            f"{sql_text(category)}, {sql_ts(event_start)}, {sql_ts(event_start + timedelta(seconds=duration))}, {duration}, "
            f"{sql_ts(event_start + timedelta(seconds=duration))});"
        )
        downtime_rows += 1

    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    lines.append("SELECT")
    lines.append(f"  {heat_count} AS heat_count,")
    lines.append(f"  {coil_count} AS slab_and_coil_count,")
    lines.append(f"  {pass_rows} AS hsm_pass_measurement_count,")
    lines.append(f"  {defect_rows} AS surface_defect_count,")
    lines.append(f"  {lab_rows} AS qa_lab_result_count,")
    lines.append(f"  {downtime_rows} AS downtime_event_count;")

    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated: {out_path}")
    print(f"Heats: {heat_count}")
    print(f"Slabs/coils: {coil_count}")
    print(f"HSM pass measurements: {pass_rows}")
    print(f"Defects: {defect_rows}")
    print(f"Lab results: {lab_rows}")
    print(f"Downtime events: {downtime_rows}")


if __name__ == "__main__":
    main()