services:
  plantprocess-api:
    environment:
      PPIQ_BUILD_COMMIT: "b9bf698"
      PPIQ_BUILD_BRANCH: "main"
      PPIQ_BUILD_UTC: "2026-06-10T09:30:22.6901382Z"
      POSTGRES_PASSWORD: "local-dev-compose-placeholder"
  plantprocess-app-web:
    environment:
      PPIQ_BUILD_COMMIT: "b9bf698"
      PPIQ_BUILD_BRANCH: "main"
      PPIQ_BUILD_UTC: "2026-06-10T09:30:22.6901382Z"
      POSTGRES_PASSWORD: "local-dev-compose-placeholder"
  plantprocess-website:
    environment:
      PPIQ_BUILD_COMMIT: "b9bf698"
      PPIQ_BUILD_BRANCH: "main"
      PPIQ_BUILD_UTC: "2026-06-10T09:30:22.6901382Z"
      POSTGRES_PASSWORD: "local-dev-compose-placeholder"
  plantprocess-workers:
    environment:
      PPIQ_BUILD_COMMIT: "b9bf698"
      PPIQ_BUILD_BRANCH: "main"
      PPIQ_BUILD_UTC: "2026-06-10T09:30:22.6901382Z"
      POSTGRES_PASSWORD: "local-dev-compose-placeholder"
