-- ============================================================================
-- PlantProcess IQ - Phase 0 / H-01 JobDefinition Seed
-- Purpose:
--   Seed DB-backed operational job records so Jobs Monitor is no longer
--   synthesized from ImportBatch rows and hard-coded placeholders.
--
-- Safe to run multiple times.
-- ============================================================================

INSERT INTO job_definitions
(
    id,
    job_code,
    job_name,
    job_type,
    target_id,
    target_type,
    schedule_expression,
    is_enabled,
    last_run_started_at_utc,
    last_run_completed_at_utc,
    last_run_duration_ms,
    last_run_status,
    last_failure_reason,
    next_run_at_utc,
    description,
    created_at_utc,
    updated_at_utc,
    is_synthetic,
    source_system,
    source_record_id,
    is_deleted,
    deleted_at_utc,
    deleted_reason
)
VALUES
(
    '00000000-0000-0000-0000-000000000101',
    'SYSTEM_IMPORT_QUEUE_PROCESSOR',
    'Import Queue Processor',
    'CanonicalRefresh',
    NULL,
    'SystemWorker',
    'Every 2 minutes',
    TRUE,
    NULL,
    NULL,
    NULL,
    'NeverRun',
    NULL,
    NULL,
    'Processes pending import batches and maps staging data into canonical records.',
    NOW() AT TIME ZONE 'UTC',
    NULL,
    FALSE,
    'PlantProcessIQ.System',
    'SYSTEM_IMPORT_QUEUE_PROCESSOR',
    FALSE,
    NULL,
    NULL
),
(
    '00000000-0000-0000-0000-000000000102',
    'SYSTEM_TELEMETRY_INGESTION',
    'Telemetry Ingestion Worker',
    'DbLinkImport',
    NULL,
    'SystemWorker',
    'Every 2 minutes',
    TRUE,
    NULL,
    NULL,
    NULL,
    'NeverRun',
    NULL,
    NULL,
    'Reads available source records into the raw staging layer.',
    NOW() AT TIME ZONE 'UTC',
    NULL,
    FALSE,
    'PlantProcessIQ.System',
    'SYSTEM_TELEMETRY_INGESTION',
    FALSE,
    NULL,
    NULL
),
(
    '00000000-0000-0000-0000-000000000103',
    'SYSTEM_DATA_QUALITY_SCAN',
    'Scheduled Data Quality Scan',
    'DataQualityScan',
    NULL,
    'SystemWorker',
    'Every 15 minutes',
    TRUE,
    NULL,
    NULL,
    NULL,
    'NeverRun',
    NULL,
    NULL,
    'Scans canonical data and staging data for data-quality issues.',
    NOW() AT TIME ZONE 'UTC',
    NULL,
    FALSE,
    'PlantProcessIQ.System',
    'SYSTEM_DATA_QUALITY_SCAN',
    FALSE,
    NULL,
    NULL
),
(
    '00000000-0000-0000-0000-000000000104',
    'SYSTEM_RISK_SCORING',
    'Scheduled Risk Scoring',
    'RiskScoring',
    NULL,
    'SystemWorker',
    'Every 15 minutes',
    TRUE,
    NULL,
    NULL,
    NULL,
    'NeverRun',
    NULL,
    NULL,
    'Calculates material/batch quality risk scores from configured rules and models.',
    NOW() AT TIME ZONE 'UTC',
    NULL,
    FALSE,
    'PlantProcessIQ.System',
    'SYSTEM_RISK_SCORING',
    FALSE,
    NULL,
    NULL
)
ON CONFLICT (job_code)
WHERE is_deleted = FALSE
DO UPDATE SET
    job_name = EXCLUDED.job_name,
    job_type = EXCLUDED.job_type,
    target_type = EXCLUDED.target_type,
    schedule_expression = EXCLUDED.schedule_expression,
    is_enabled = EXCLUDED.is_enabled,
    description = EXCLUDED.description,
    updated_at_utc = NOW() AT TIME ZONE 'UTC';