-- ============================================================================
-- PlantProcess IQ - Phase 1 System Dashboard Templates
-- Purpose:
--   Seed five read-only system dashboards for customer discovery/demo.
--
-- Templates:
--   1. Quality Overview
--   2. Risk Dashboard
--   3. Data Quality
--   4. Correlation Explorer
--   5. Material Investigation Launcher
--
-- Safe to run multiple times.
-- ============================================================================

BEGIN;

INSERT INTO dashboard_definitions
(
    id,
    user_id,
    dashboard_code,
    name,
    description,
    layout_json,
    is_default,
    is_system_template,
    is_active,
    created_at_utc,
    updated_at_utc,
    is_synthetic,
    source_system,
    source_record_id,
    is_deleted,
    deleted_at_utc,
    deleted_reason
)
VALUES
(
    '10000000-0000-0000-0000-000000000001',
    NULL,
    'QUALITY_OVERVIEW',
    'Quality Overview',
    'System dashboard template for production volume, defect rate, defect trend, and quality breakdown.',
    '{}',
    TRUE,
    TRUE,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'QUALITY_OVERVIEW',
    FALSE,
    NULL,
    NULL
),
(
    '10000000-0000-0000-0000-000000000002',
    NULL,
    'RISK_DASHBOARD',
    'Risk Dashboard',
    'System dashboard template for risk score distribution, high-risk material monitoring, and top risk contributors.',
    '{}',
    FALSE,
    TRUE,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'RISK_DASHBOARD',
    FALSE,
    NULL,
    NULL
),
(
    '10000000-0000-0000-0000-000000000003',
    NULL,
    'DATA_QUALITY',
    'Data Quality',
    'System dashboard template for data-quality issue count, severity, issue type, and source-system visibility.',
    '{}',
    FALSE,
    TRUE,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'DATA_QUALITY',
    FALSE,
    NULL,
    NULL
),
(
    '10000000-0000-0000-0000-000000000004',
    NULL,
    'CORRELATION_EXPLORER',
    'Correlation Explorer',
    'System dashboard template for parameter, defect, equipment, source-system and time-based correlation exploration.',
    '{}',
    FALSE,
    TRUE,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'CORRELATION_EXPLORER',
    FALSE,
    NULL,
    NULL
),
(
    '10000000-0000-0000-0000-000000000005',
    NULL,
    'MATERIAL_INVESTIGATION_LAUNCHER',
    'Material Investigation Launcher',
    'System dashboard template to find materials/batches and launch investigation workflows.',
    '{}',
    FALSE,
    TRUE,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'MATERIAL_INVESTIGATION_LAUNCHER',
    FALSE,
    NULL,
    NULL
)
ON CONFLICT (dashboard_code)
WHERE is_deleted = FALSE
DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_system_template = TRUE,
    is_active = TRUE,
    updated_at_utc = NOW() AT TIME ZONE 'UTC';

-- ----------------------------------------------------------------------------
-- Quality Overview widgets
-- ----------------------------------------------------------------------------
INSERT INTO dashboard_widget_definitions
(
    id,
    dashboard_definition_id,
    widget_code,
    widget_title,
    widget_type,
    chart_type,
    dimension_code,
    measure_code,
    parameter_code,
    filter_json,
    layout_json,
    display_options_json,
    sort_order,
    is_active,
    created_at_utc,
    updated_at_utc,
    is_synthetic,
    source_system,
    source_record_id,
    is_deleted,
    deleted_at_utc,
    deleted_reason
)
VALUES
(
    '11000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000001',
    'QUALITY_DEFECT_TREND',
    'Defect Rate Trend',
    'chart',
    'line',
    'day',
    'defectRate',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":0,"w":8,"h":8}}',
    '{"maxRows":90,"rawRowLimit":1000}',
    1,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'QUALITY_DEFECT_TREND',
    FALSE,
    NULL,
    NULL
),
(
    '11000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000001',
    'QUALITY_DEFECT_BREAKDOWN',
    'Defect Breakdown',
    'chart',
    'bar',
    'defectType',
    'defectCount',
    NULL,
    '{}',
    '{"lg":{"x":8,"y":0,"w":4,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    2,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'QUALITY_DEFECT_BREAKDOWN',
    FALSE,
    NULL,
    NULL
),
(
    '11000000-0000-0000-0000-000000000003',
    '10000000-0000-0000-0000-000000000001',
    'QUALITY_BY_MATERIAL_TYPE',
    'Material Count by Type',
    'chart',
    'pie',
    'materialUnitType',
    'materialCount',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":8,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    3,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'QUALITY_BY_MATERIAL_TYPE',
    FALSE,
    NULL,
    NULL
),

-- Risk Dashboard widgets
(
    '12000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000002',
    'RISK_BY_CLASS',
    'Risk Score by Class',
    'chart',
    'bar',
    'riskClass',
    'riskScore',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    1,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'RISK_BY_CLASS',
    FALSE,
    NULL,
    NULL
),
(
    '12000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000002',
    'RISK_BY_EQUIPMENT',
    'Risk by Equipment',
    'chart',
    'bar',
    'equipment',
    'riskScore',
    NULL,
    '{}',
    '{"lg":{"x":6,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    2,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'RISK_BY_EQUIPMENT',
    FALSE,
    NULL,
    NULL
),

-- Data Quality widgets
(
    '13000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000003',
    'DQ_BY_SOURCE',
    'Data Quality Issues by Source',
    'chart',
    'bar',
    'sourceSystem',
    'dataQualityIssueCount',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    1,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'DQ_BY_SOURCE',
    FALSE,
    NULL,
    NULL
),
(
    '13000000-0000-0000-0000-000000000002',
    '10000000-0000-0000-0000-000000000003',
    'DQ_BY_TYPE',
    'Data Quality Issues by Type',
    'chart',
    'bar',
    'defectType',
    'dataQualityIssueCount',
    NULL,
    '{}',
    '{"lg":{"x":6,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    2,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'DQ_BY_TYPE',
    FALSE,
    NULL,
    NULL
),

-- Correlation Explorer widgets
(
    '14000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000004',
    'CORR_PARAMETER_AVG_BY_EQUIPMENT',
    'Average Parameter Value by Equipment',
    'chart',
    'bar',
    'equipment',
    'avgParameterValue',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    1,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'CORR_PARAMETER_AVG_BY_EQUIPMENT',
    FALSE,
    NULL,
    NULL
),

-- Material Investigation Launcher widgets
(
    '15000000-0000-0000-0000-000000000001',
    '10000000-0000-0000-0000-000000000005',
    'INV_MATERIAL_BY_TYPE',
    'Material Count by Type',
    'chart',
    'bar',
    'materialUnitType',
    'materialCount',
    NULL,
    '{}',
    '{"lg":{"x":0,"y":0,"w":6,"h":8}}',
    '{"maxRows":20,"rawRowLimit":1000}',
    1,
    TRUE,
    NOW() AT TIME ZONE 'UTC',
    NULL,
    TRUE,
    'PlantProcessIQ.SystemTemplates',
    'INV_MATERIAL_BY_TYPE',
    FALSE,
    NULL,
    NULL
)
ON CONFLICT (widget_code)
WHERE is_deleted = FALSE
DO UPDATE SET
    widget_title = EXCLUDED.widget_title,
    widget_type = EXCLUDED.widget_type,
    chart_type = EXCLUDED.chart_type,
    dimension_code = EXCLUDED.dimension_code,
    measure_code = EXCLUDED.measure_code,
    parameter_code = EXCLUDED.parameter_code,
    filter_json = EXCLUDED.filter_json,
    layout_json = EXCLUDED.layout_json,
    display_options_json = EXCLUDED.display_options_json,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE,
    updated_at_utc = NOW() AT TIME ZONE 'UTC';

COMMIT;