-- ============================================================================
-- RETIRED. This file no longer creates system dashboard templates.
--
-- Why:
--   Three mechanisms created the same product system templates. This seed used
--   INSERT ... ON CONFLICT (widget_code) DO UPDATE, so every replay silently
--   overwrote whatever the runtime had reconciled, and a companion repair
--   script then rewrote the same rows again. Live evidence: DQ_BY_TYPE was
--   inserted here as defectType and persists in the application database as
--   materialUnitType, because a different authority won.
--
-- Single authority:
--   DashboardDefinitionService.EnsureSystemTemplatesAsync is the operational
--   authority for product system templates. It is idempotent, repairs drift,
--   runs on every deployment regardless of which SQL was replayed, and is the
--   only mechanism that can honour a product that starts empty.
--
-- Two widgets were not carried across:
--   CORR_PARAMETER_AVG_BY_EQUIPMENT declared avgParameterValue with a null
--     parameter. A product template cannot know which parameters a plant has,
--     and cannot choose one without embedding plant-specific vocabulary, so the
--     widget is retired rather than given an invented default.
--   DQ_BY_TYPE was rewritten in place by the repair script into the definition the
--     runtime authority already publishes as DQ_BY_MATERIAL_TYPE, so it is a duplicate
--     under a legacy code rather than a broken widget.
--
-- Existing databases are reconciled by:
--   Backend/database/scripts/830_system_template_single_authority.sql
--
-- This file is kept as a deliberate no-op so any replay list that still names
-- it continues to succeed. Do not reintroduce template writes here.
-- ============================================================================

SELECT 'system dashboard templates are created by the runtime authority; this seed is retired' AS notice;
