// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantProcess.Infrastructure.Persistence;

#nullable disable

namespace PlantProcess.Infrastructure.Migrations
{
    [DbContext(typeof(PlantProcessDbContext))]
    [Migration("20260507074459_InitialCanonicalModel")]
    partial class InitialCanonicalModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantProcess.Domain.Entities.DataQualityIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AffectedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("affected_entity_id");

                    b.Property<string>("AffectedEntityName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("affected_entity_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("issue_type");

                    b.Property<Guid?>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_data_quality_issues");

                    b.HasIndex("AffectedEntityId")
                        .HasDatabaseName("ix_data_quality_issues_affected_entity_id");

                    b.HasIndex("IssueType")
                        .HasDatabaseName("ix_data_quality_issues_issue_type");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_data_quality_issues_material_unit_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_data_quality_issues_severity");

                    b.ToTable("data_quality_issues", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.DefectCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefectCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("defect_category");

                    b.Property<string>("DefectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("defect_code");

                    b.Property<string>("DefectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("defect_name");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("IndustryTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry_template");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_defect_catalogs");

                    b.HasIndex("DefectCategory")
                        .HasDatabaseName("ix_defect_catalogs_defect_category");

                    b.HasIndex("DefectCode")
                        .IsUnique()
                        .HasDatabaseName("ix_defect_catalogs_defect_code");

                    b.HasIndex("IndustryTemplate")
                        .HasDatabaseName("ix_defect_catalogs_industry_template");

                    b.ToTable("defect_catalogs", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.DowntimeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DowntimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("downtime_type");

                    b.Property<DateTime?>("EndedAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at_local");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid?>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<Guid?>("ProcessStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_step_execution_id");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime>("StartedAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at_local");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_downtime_events");

                    b.HasIndex("DowntimeType")
                        .HasDatabaseName("ix_downtime_events_downtime_type");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_downtime_events_equipment_id");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_downtime_events_material_unit_id");

                    b.HasIndex("ProcessStepExecutionId")
                        .HasDatabaseName("ix_downtime_events_process_step_execution_id");

                    b.HasIndex("StartedAtLocal")
                        .HasDatabaseName("ix_downtime_events_started_at_local");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_downtime_events_started_at_utc");

                    b.ToTable("downtime_events", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.GenealogyEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildMaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_material_unit_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<DateTime?>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid>("ParentMaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_material_unit_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("relationship_type");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_genealogy_edges");

                    b.HasIndex("ChildMaterialUnitId")
                        .HasDatabaseName("ix_genealogy_edges_child_material_unit_id");

                    b.HasIndex("ParentMaterialUnitId")
                        .HasDatabaseName("ix_genealogy_edges_parent_material_unit_id");

                    b.HasIndex("ParentMaterialUnitId", "ChildMaterialUnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_genealogy_edges_parent_material_unit_id_child_material_unit");

                    b.ToTable("genealogy_edges", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.MaterialAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AliasCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias_code");

                    b.Property<string>("AliasType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_material_aliases");

                    b.HasIndex("AliasCode")
                        .HasDatabaseName("ix_material_aliases_alias_code");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_material_aliases_material_unit_id");

                    b.HasIndex("SourceSystem")
                        .HasDatabaseName("ix_material_aliases_source_system");

                    b.HasIndex("MaterialUnitId", "AliasCode", "SourceSystem")
                        .IsUnique()
                        .HasDatabaseName("ix_material_aliases_material_unit_id_alias_code_source_system");

                    b.ToTable("material_aliases", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.MaterialUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("GradeOrRecipe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grade_or_recipe");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_code");

                    b.Property<string>("MaterialUnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_unit_type");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<string>("ProductFamily")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_family");

                    b.Property<DateTime?>("ProductionEndLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("production_end_local");

                    b.Property<DateTime?>("ProductionEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_end_utc");

                    b.Property<DateTime?>("ProductionStartLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("production_start_local");

                    b.Property<DateTime?>("ProductionStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_start_utc");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_material_units");

                    b.HasIndex("MaterialCode")
                        .IsUnique()
                        .HasDatabaseName("ix_material_units_material_code");

                    b.HasIndex("MaterialUnitType")
                        .HasDatabaseName("ix_material_units_material_unit_type");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_material_units_site_id");

                    b.HasIndex("MaterialUnitType", "GradeOrRecipe")
                        .HasDatabaseName("ix_material_units_material_unit_type_grade_or_recipe");

                    b.HasIndex("SiteId", "MaterialUnitType")
                        .HasDatabaseName("ix_material_units_site_id_material_unit_type");

                    b.ToTable("material_units", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ParameterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<decimal?>("ExpectedMaxValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("expected_max_value");

                    b.Property<decimal?>("ExpectedMinValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("expected_min_value");

                    b.Property<string>("IndustryTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry_template");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("ParameterCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_category");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parameter_name");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("value_type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_parameter_definitions");

                    b.HasIndex("IndustryTemplate")
                        .HasDatabaseName("ix_parameter_definitions_industry_template");

                    b.HasIndex("ParameterCategory")
                        .HasDatabaseName("ix_parameter_definitions_parameter_category");

                    b.HasIndex("ParameterCode")
                        .IsUnique()
                        .HasDatabaseName("ix_parameter_definitions_parameter_code");

                    b.ToTable("parameter_definitions", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ParameterObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("numeric_value");

                    b.Property<DateTime>("ObservedAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("observed_at_local");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("ParameterDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("parameter_definition_id");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<Guid?>("ProcessStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_step_execution_id");

                    b.Property<string>("QualityFlag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("quality_flag");

                    b.Property<string>("RawValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("raw_value");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text_value");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_parameter_observations");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_parameter_observations_equipment_id");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_parameter_observations_material_unit_id");

                    b.HasIndex("ObservedAtLocal")
                        .HasDatabaseName("ix_parameter_observations_observed_at_local");

                    b.HasIndex("ObservedAtUtc")
                        .HasDatabaseName("ix_parameter_observations_observed_at_utc");

                    b.HasIndex("ParameterDefinitionId")
                        .HasDatabaseName("ix_parameter_observations_parameter_definition_id");

                    b.HasIndex("ProcessStepExecutionId")
                        .HasDatabaseName("ix_parameter_observations_process_step_execution_id");

                    b.HasIndex("MaterialUnitId", "ParameterDefinitionId", "ObservedAtUtc")
                        .HasDatabaseName("ix_parameter_observations_material_unit_id_parameter_definitio");

                    b.ToTable("parameter_observations", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ProcessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTime>("EventAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("event_at_local");

                    b.Property<DateTime>("EventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("EventValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_value");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid?>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<Guid?>("ProcessStepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_step_execution_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_process_events");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_process_events_equipment_id");

                    b.HasIndex("EventAtUtc")
                        .HasDatabaseName("ix_process_events_event_at_utc");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_process_events_event_type");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_process_events_material_unit_id");

                    b.HasIndex("ProcessStepExecutionId")
                        .HasDatabaseName("ix_process_events_process_step_execution_id");

                    b.HasIndex("EventType", "EventAtUtc")
                        .HasDatabaseName("ix_process_events_event_type_event_at_utc");

                    b.ToTable("process_events", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ProcessStepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CrewCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crew_code");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<DateTime?>("EndedAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ended_at_local");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("execution_status");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("LineCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_code");

                    b.Property<Guid>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("OperationCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_code");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation_type");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime>("StartedAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("started_at_local");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_process_step_executions");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_process_step_executions_equipment_id");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_process_step_executions_material_unit_id");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("ix_process_step_executions_operation_type");

                    b.HasIndex("StartedAtLocal")
                        .HasDatabaseName("ix_process_step_executions_started_at_local");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_process_step_executions_started_at_utc");

                    b.HasIndex("CrewCode", "StartedAtLocal")
                        .HasDatabaseName("ix_process_step_executions_crew_code_started_at_local");

                    b.HasIndex("OperationType", "StartedAtLocal")
                        .HasDatabaseName("ix_process_step_executions_operation_type_started_at_local");

                    b.HasIndex("MaterialUnitId", "OperationType", "StartedAtUtc")
                        .HasDatabaseName("ix_process_step_executions_material_unit_id_operation_type_sta");

                    b.ToTable("process_step_executions", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.QualityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Decision")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decision");

                    b.Property<Guid?>("DefectCatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_catalog_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("event_at_local");

                    b.Property<DateTime>("EventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<Guid>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_quality_events");

                    b.HasIndex("DefectCatalogId")
                        .HasDatabaseName("ix_quality_events_defect_catalog_id");

                    b.HasIndex("EventAtLocal")
                        .HasDatabaseName("ix_quality_events_event_at_local");

                    b.HasIndex("EventAtUtc")
                        .HasDatabaseName("ix_quality_events_event_at_utc");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_quality_events_event_type");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_quality_events_material_unit_id");

                    b.HasIndex("MaterialUnitId", "EventType", "EventAtUtc")
                        .HasDatabaseName("ix_quality_events_material_unit_id_event_type_event_at_utc");

                    b.ToTable("quality_events", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.RiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("DeletedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deleted_reason");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_synthetic");

                    b.Property<string>("MainContributorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("main_contributors_json");

                    b.Property<Guid>("MaterialUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_version");

                    b.Property<string>("PlantTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plant_time_zone_id");

                    b.Property<int>("PlantUtcOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("plant_utc_offset_minutes");

                    b.Property<string>("RiskClass")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_class");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("risk_type");

                    b.Property<decimal>("Score")
                        .HasPrecision(8, 6)
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("score");

                    b.Property<DateTime>("ScoredAtLocal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scored_at_local");

                    b.Property<DateTime>("ScoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at_utc");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_system");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_risk_scores");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_risk_scores_material_unit_id");

                    b.HasIndex("RiskType")
                        .HasDatabaseName("ix_risk_scores_risk_type");

                    b.HasIndex("ScoredAtUtc")
                        .HasDatabaseName("ix_risk_scores_scored_at_utc");

                    b.HasIndex("MaterialUnitId", "RiskType", "ScoredAtUtc")
                        .HasDatabaseName("ix_risk_scores_material_unit_id_risk_type_scored_at_utc");

                    b.ToTable("risk_scores", (string)null);
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.DataQualityIssue", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_data_quality_issues_material_units_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.DowntimeEvent", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_downtime_events_material_units_material_unit_id");

                    b.HasOne("PlantProcess.Domain.Entities.ProcessStepExecution", null)
                        .WithMany()
                        .HasForeignKey("ProcessStepExecutionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_downtime_events_process_step_executions_process_step_execut");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.GenealogyEdge", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("ChildMaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_genealogy_edges_material_units_child_material_unit_id");

                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentMaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_genealogy_edges_material_units_parent_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.MaterialAlias", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany("Aliases")
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_aliases_material_units_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ParameterObservation", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parameter_observations_material_units_material_unit_id");

                    b.HasOne("PlantProcess.Domain.Entities.ParameterDefinition", null)
                        .WithMany()
                        .HasForeignKey("ParameterDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parameter_observations_parameter_definitions_parameter_defi");

                    b.HasOne("PlantProcess.Domain.Entities.ProcessStepExecution", null)
                        .WithMany()
                        .HasForeignKey("ProcessStepExecutionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_parameter_observations_process_step_executions_process_step");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ProcessEvent", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_process_events_material_units_material_unit_id");

                    b.HasOne("PlantProcess.Domain.Entities.ProcessStepExecution", null)
                        .WithMany()
                        .HasForeignKey("ProcessStepExecutionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_process_events_process_step_executions_process_step_executi");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.ProcessStepExecution", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_process_step_executions_material_units_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.QualityEvent", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.DefectCatalog", null)
                        .WithMany()
                        .HasForeignKey("DefectCatalogId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quality_events_defect_catalogs_defect_catalog_id");

                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quality_events_material_units_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.RiskScore", b =>
                {
                    b.HasOne("PlantProcess.Domain.Entities.MaterialUnit", null)
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_risk_scores_material_units_material_unit_id");
                });

            modelBuilder.Entity("PlantProcess.Domain.Entities.MaterialUnit", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
