SET HEADING OFF
SET FEEDBACK OFF
SET VERIFY OFF
SET ECHO OFF
SET PAGESIZE 0
SET LINESIZE 200
WHENEVER SQLERROR EXIT SQL.SQLCODE
SELECT COUNT(*) FROM caster_sequences WHERE sequence_id = 'ADV_SEQ4002';
EXIT;
