// Known-answer decoding.
//
// EVERY EXPECTED VALUE AND EVERY FIXTURE BYTE IN THIS FILE WAS PRODUCED OUTSIDE THE
// DECODER UNDER TEST, with Python's struct module, and pasted in as a literal. A
// fixture generated by the implementation proves only that the implementation
// agrees with itself.
using System.Globalization;
using System.Text.Json;
using PlantProcess.Application.Integration.Acquisition;
using PlantProcess.Application.Integration.Acquisition.Decoding;

namespace PlantProcess.Application.UnitTests.Integration;

public sealed class RawBlockDecoderTests
{
    private static readonly Guid Counter = Guid.Parse("aaaaaaaa-0000-0000-0000-000000000001");
    private static readonly Guid Temperature = Guid.Parse("aaaaaaaa-0000-0000-0000-000000000002");
    private static readonly Guid Alarm = Guid.Parse("aaaaaaaa-0000-0000-0000-000000000003");
    private static readonly Guid Tag = Guid.Parse("aaaaaaaa-0000-0000-0000-000000000004");
    private static readonly Guid Status = Guid.Parse("aaaaaaaa-0000-0000-0000-000000000005");

    private static readonly Guid Energy = Guid.Parse("bbbbbbbb-0000-0000-0000-000000000001");
    private static readonly Guid Readings = Guid.Parse("bbbbbbbb-0000-0000-0000-000000000002");
    private static readonly Guid Signed = Guid.Parse("bbbbbbbb-0000-0000-0000-000000000003");
    private static readonly Guid Unsigned = Guid.Parse("bbbbbbbb-0000-0000-0000-000000000004");

    private static readonly Guid Governance = Guid.Parse("cccccccc-0000-0000-0000-000000000001");

    // struct.pack: >I 1234 | <f -12.5 | bit 3 set | ascii "AB12" NUL padded | 0xFF
    private const string FixtureA = "000004d2000048c108414231320000ff";

    // >I 0x01020304 with its two 16-bit words swapped | >h -1, 0, 32767 | >b -128 | 200
    private const string FixtureB = "03040102ffff00007fff80c8";

    // >h -32768 | >H 65535 | >q long.MinValue | >Q ulong.MaxValue | >f 0.1
    private const string FixtureC = "8000ffff8000000000000000ffffffffffffffff3dcccccd";

    private static byte[] Bytes(string hex) => Convert.FromHexString(hex);

    private static JsonElement Layout(string json) => JsonDocument.Parse(json).RootElement.Clone();

    private static string LayoutA(int regionBytes = 16) =>
        "{\"layoutKind\":\"raw_block\",\"regionBytes\":" + regionBytes + ",\"members\":[" +
        Member(Counter, "uint32", 0, ",\"byteOrder\":\"big\"") + "," +
        Member(Temperature, "float32", 4, ",\"byteOrder\":\"little\"") + "," +
        Member(Alarm, "boolean", 8, ",\"bitOffset\":3") + "," +
        Member(Tag, "string", 9, ",\"encoding\":\"ascii\",\"length\":6") + "," +
        Member(Status, "uint8", 15) + "]}";

    private static string LayoutB() =>
        "{\"layoutKind\":\"raw_block\",\"regionBytes\":12,\"members\":[" +
        Member(Energy, "uint32", 0, ",\"byteOrder\":\"big\",\"wordOrder\":\"little\"") + "," +
        Member(Readings, "int16", 4, ",\"byteOrder\":\"big\",\"arrayCount\":3") + "," +
        Member(Signed, "int8", 10) + "," +
        Member(Unsigned, "uint8", 11) + "]}";

    private static string Member(Guid id, string type, int byteOffset, string extra = "") =>
        "{\"fieldId\":\"" + id.ToString("D") + "\",\"type\":\"" + type + "\",\"byteOffset\":" + byteOffset + extra + "}";

    private static string TextOf(RawBlockDecodeResult result, Guid fieldId) =>
        result.Values.Single(v => v.FieldId == fieldId).CanonicalText;

    // ------------------------------------------------------------- layout A

    [Fact]
    public void A_mixed_layout_decodes_to_its_independently_authored_answers()
    {
        var result = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA));

        Assert.True(result.Accepted, string.Join("; ", result.Diagnostics.Select(d => d.Code + " " + d.Detail)));
        Assert.Equal(5, result.Values.Count);
        Assert.Equal("1234", TextOf(result, Counter));
        Assert.Equal("-12.5", TextOf(result, Temperature));
        Assert.Equal("true", TextOf(result, Alarm));
        Assert.Equal("AB12", TextOf(result, Tag));
        Assert.Equal("255", TextOf(result, Status));

        // The payload hash is over the bytes as delivered, and the layout hash is the
        // authority's own, so an accepted record can name exactly what it decoded.
        Assert.Equal(64, result.PayloadHash.Length);
        Assert.Equal(64, result.LayoutSemanticHash.Length);
        Assert.Equal(16, result.PayloadBytes);
    }

    [Fact]
    public void A_bit_is_read_from_its_own_position_and_not_from_the_byte()
    {
        // Only bit 3 of byte 8 is set in the fixture; every other bit of that byte is 0.
        for (var bit = 0; bit <= 7; bit++)
        {
            var layout = "{\"layoutKind\":\"raw_block\",\"regionBytes\":16,\"members\":[" +
                         Member(Alarm, "boolean", 8, ",\"bitOffset\":" + bit) + "]}";
            var result = RawBlockDecoder.Decode(Layout(layout), 1, Bytes(FixtureA));
            Assert.True(result.Accepted);
            Assert.Equal(bit == 3 ? "true" : "false", TextOf(result, Alarm));
        }
    }

    // ------------------------------------------------------------- layout B

    [Fact]
    public void A_word_swapped_layout_and_a_bounded_array_decode_to_their_authored_answers()
    {
        var result = RawBlockDecoder.Decode(Layout(LayoutB()), 4, Bytes(FixtureB));

        Assert.True(result.Accepted, string.Join("; ", result.Diagnostics.Select(d => d.Code + " " + d.Detail)));
        Assert.Equal("16909060", TextOf(result, Energy));
        Assert.Equal("[-1,0,32767]", TextOf(result, Readings));
        Assert.Equal("-128", TextOf(result, Signed));
        Assert.Equal("200", TextOf(result, Unsigned));
        Assert.Equal(3, result.Values.Single(v => v.FieldId == Readings).ArrayCount);
    }

    [Fact]
    public void Byte_order_is_obeyed_rather_than_assumed()
    {
        // The same four bytes, three declared orders, three different answers.
        var raw = Bytes("03040102");
        string One(string extra) =>
            "{\"layoutKind\":\"raw_block\",\"regionBytes\":4,\"members\":[" + Member(Energy, "uint32", 0, extra) + "]}";

        var big = RawBlockDecoder.Decode(Layout(One(",\"byteOrder\":\"big\"")), 1, raw);
        var little = RawBlockDecoder.Decode(Layout(One(",\"byteOrder\":\"little\"")), 1, raw);
        var swapped = RawBlockDecoder.Decode(Layout(One(",\"byteOrder\":\"big\",\"wordOrder\":\"little\"")), 1, raw);

        Assert.Equal("50594050", TextOf(big, Energy));        // 0x03040102
        Assert.Equal("33620995", TextOf(little, Energy));     // 0x02010403, from struct.unpack(">I", raw[::-1])
        Assert.Equal("16909060", TextOf(swapped, Energy));    // 0x01020304
    }

    // --------------------------------------------------------- boundaries

    [Fact]
    public void Numeric_boundaries_round_trip_exactly()
    {
        var layout = "{\"layoutKind\":\"raw_block\",\"regionBytes\":24,\"members\":[" +
            Member(Counter, "int16", 0, ",\"byteOrder\":\"big\"") + "," +
            Member(Temperature, "uint16", 2, ",\"byteOrder\":\"big\"") + "," +
            Member(Alarm, "int64", 4, ",\"byteOrder\":\"big\"") + "," +
            Member(Tag, "uint64", 12, ",\"byteOrder\":\"big\"") + "," +
            Member(Status, "float32", 20, ",\"byteOrder\":\"big\"") + "]}";

        var result = RawBlockDecoder.Decode(Layout(layout), 7, Bytes(FixtureC));

        Assert.True(result.Accepted, string.Join("; ", result.Diagnostics.Select(d => d.Code)));
        Assert.Equal("-32768", TextOf(result, Counter));
        Assert.Equal("65535", TextOf(result, Temperature));
        Assert.Equal("-9223372036854775808", TextOf(result, Alarm));
        Assert.Equal("18446744073709551615", TextOf(result, Tag));

        // THE BOXING TRAP, ASSERTED: a switch expression whose arms are sbyte..double
        // has a best common type of double, so every integer would arrive as a rounded
        // double and nothing would fail to compile. Both the CLR type and the exact
        // value are checked, for values that cannot survive a double.
        Assert.IsType<short>(result.Values.Single(v => v.FieldId == Counter).Value!);
        Assert.IsType<ushort>(result.Values.Single(v => v.FieldId == Temperature).Value!);
        Assert.IsType<long>(result.Values.Single(v => v.FieldId == Alarm).Value!);
        Assert.IsType<ulong>(result.Values.Single(v => v.FieldId == Tag).Value!);
        Assert.IsType<float>(result.Values.Single(v => v.FieldId == Status).Value!);
        Assert.Equal(long.MinValue, (long)result.Values.Single(v => v.FieldId == Alarm).Value!);
        Assert.Equal(ulong.MaxValue, (ulong)result.Values.Single(v => v.FieldId == Tag).Value!);
        Assert.Equal(-32768, (short)result.Values.Single(v => v.FieldId == Counter).Value!);
        Assert.Equal((ushort)65535, (ushort)result.Values.Single(v => v.FieldId == Temperature).Value!);

        // The identity document carries those exact texts, so a 64-bit identity member
        // cannot be collapsed by a lossy conversion on the way into a hash.
        var identity = SourceEventIdentity.Derive(Governance, 7, result, new[] { Alarm, Tag });
        Assert.True(identity.IsAccepted, identity.Refusal?.Detail);
        Assert.Contains("-9223372036854775808", identity.Value!.CanonicalDocument);
        Assert.Contains("18446744073709551615", identity.Value.CanonicalDocument);

        // 0.1 as float32 is 0.100000001490116119384765625; the decoder reports what the
        // bytes hold, never a rounded reading of them.
        Assert.Equal("0.1", TextOf(result, Status));
        Assert.Equal(0.1f, (float)result.Values.Single(v => v.FieldId == Status).Value!);
        Assert.NotEqual(0.1d, Convert.ToDouble(result.Values.Single(v => v.FieldId == Status).Value!, CultureInfo.InvariantCulture));
    }

    // ------------------------------------------------------------ refusals

    [Fact]
    public void A_short_payload_is_refused_and_never_padded()
    {
        var result = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA).AsSpan(0, 12));

        Assert.False(result.Accepted);
        Assert.Empty(result.Values);
        Assert.Equal(DecodeCodes.PayloadTruncated, result.Diagnostics[0].Code);
    }

    [Fact]
    public void Unexplained_trailing_bytes_are_refused_unless_the_budget_allows_them()
    {
        var longer = Bytes(FixtureA + "aabb");

        var strict = RawBlockDecoder.Decode(Layout(LayoutA()), 1, longer);
        Assert.False(strict.Accepted);
        Assert.Equal(DecodeCodes.PayloadTrailingBytes, strict.Diagnostics[0].Code);

        var permitted = RawBlockDecoder.Decode(Layout(LayoutA()), 1, longer, DecodeBudget.Default with { AllowTrailingBytes = true });
        Assert.True(permitted.Accepted);
        Assert.Equal("1234", TextOf(permitted, Counter));
    }

    [Fact]
    public void Exhausted_budgets_refuse_rather_than_truncate()
    {
        var payload = RawBlockDecoder.Decode(
            Layout(LayoutA()), 1, Bytes(FixtureA), DecodeBudget.Default with { MaxPayloadBytes = 8 });
        Assert.False(payload.Accepted);
        Assert.Equal(DecodeCodes.PayloadTooLarge, payload.Diagnostics[0].Code);

        var members = RawBlockDecoder.Decode(
            Layout(LayoutA()), 1, Bytes(FixtureA), DecodeBudget.Default with { MaxMembers = 2 });
        Assert.False(members.Accepted);
        Assert.Equal(DecodeCodes.BudgetExhausted, members.Diagnostics[0].Code);

        var allocation = RawBlockDecoder.Decode(
            Layout(LayoutA()), 1, Bytes(FixtureA), DecodeBudget.Default with { MaxDecodedBytes = 4 });
        Assert.False(allocation.Accepted);
        Assert.Equal(DecodeCodes.BudgetExhausted, allocation.Diagnostics[0].Code);

        var arrays = RawBlockDecoder.Decode(
            Layout(LayoutB()), 4, Bytes(FixtureB), DecodeBudget.Default with { MaxArrayElements = 2 });
        Assert.False(arrays.Accepted);
        Assert.Equal(DecodeCodes.BudgetExhausted, arrays.Diagnostics[0].Code);
    }

    [Fact]
    public void An_invalid_layout_is_refused_by_its_own_authority_before_a_bit_is_read()
    {
        // Overlap, a bit position that does not exist, and a type with no codec: each
        // is refused by the layout authority, so the decoder never becomes a second
        // grammar that might disagree with it.
        var overlap = "{\"layoutKind\":\"raw_block\",\"regionBytes\":16,\"members\":[" +
            Member(Counter, "uint32", 0, ",\"byteOrder\":\"big\"") + "," +
            Member(Temperature, "uint16", 2, ",\"byteOrder\":\"big\"") + "]}";
        var badBit = "{\"layoutKind\":\"raw_block\",\"regionBytes\":16,\"members\":[" +
            Member(Alarm, "boolean", 8, ",\"bitOffset\":8") + "]}";
        var noCodec = "{\"layoutKind\":\"raw_block\",\"regionBytes\":16,\"members\":[" +
            Member(Counter, "decimal", 0) + "]}";
        var outside = "{\"layoutKind\":\"raw_block\",\"regionBytes\":4,\"members\":[" +
            Member(Counter, "int64", 0, ",\"byteOrder\":\"big\"") + "]}";

        foreach (var layout in new[] { overlap, badBit, noCodec, outside })
        {
            var result = RawBlockDecoder.Decode(Layout(layout), 1, Bytes(FixtureA));
            Assert.False(result.Accepted);
            Assert.Equal(DecodeCodes.LayoutInvalid, result.Diagnostics[0].Code);
            Assert.Empty(result.Values);
        }
    }

    [Fact]
    public void Bytes_that_are_not_the_declared_encoding_are_refused_not_reinterpreted()
    {
        // 0xC3 0x28 is invalid UTF-8 and out of range for ASCII.
        var payload = Bytes("000004d2000048c108c328313200 00ff".Replace(" ", string.Empty));

        var ascii = RawBlockDecoder.Decode(Layout(LayoutA()), 1, payload);
        Assert.False(ascii.Accepted);
        Assert.Equal(DecodeCodes.ValueNotDecodable, ascii.Diagnostics[0].Code);

        var utf8Layout = LayoutA().Replace("\"encoding\":\"ascii\"", "\"encoding\":\"utf8\"");
        var utf8 = RawBlockDecoder.Decode(Layout(utf8Layout), 1, payload);
        Assert.False(utf8.Accepted);
        Assert.Equal(DecodeCodes.ValueNotDecodable, utf8.Diagnostics[0].Code);

        // The same bytes ARE valid latin1, and that is a different declared answer.
        var latin1Layout = LayoutA().Replace("\"encoding\":\"ascii\"", "\"encoding\":\"latin1\"");
        var latin1 = RawBlockDecoder.Decode(Layout(latin1Layout), 1, payload);
        Assert.True(latin1.Accepted);
    }

    // ------------------------------------------------- identity invariance

    [Fact]
    public void A_display_label_changes_neither_decoding_nor_identity()
    {
        var locator = "{\"kind\":\"raw_member\",\"region\":\"block1\",\"path\":\"counter\"}";
        var before = FieldDeclarationKernel.Normalize("OpcUaHistorian", new FieldDeclarationRequest(
            Counter, "counter", "Counter", "int32", null, null, new[] { "event_identity" },
            JsonDocument.Parse(locator).RootElement.Clone(), null, "same_field"));
        var after = FieldDeclarationKernel.Normalize("OpcUaHistorian", new FieldDeclarationRequest(
            Counter, "counter", "Piece counter (renamed)", "int32", null, null, new[] { "event_identity" },
            JsonDocument.Parse(locator).RootElement.Clone(), null, "same_field"));

        // The label moves the revision's semantic hash and nothing else: same identity,
        // same locator, and therefore the same bytes decoded the same way.
        Assert.NotEqual(before.Value!.SemanticHash, after.Value!.SemanticHash);
        Assert.Equal(before.Value.Locator.Identity, after.Value.Locator.Identity);
        Assert.Equal(before.Value.FieldId, after.Value.FieldId);

        var first = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA));
        var second = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA));
        Assert.Equal(TextOf(first, Counter), TextOf(second, Counter));

        var identityFields = new[] { Counter };
        var one = SourceEventIdentity.Derive(Governance, 1, first, identityFields);
        var two = SourceEventIdentity.Derive(Governance, 1, second, identityFields);
        Assert.Equal(one.Value!.Value, two.Value!.Value);
    }

    [Fact]
    public void A_replayed_delivery_keeps_the_event_identity_and_a_retry_never_mints_one()
    {
        var identityFields = new[] { Counter, Tag };
        var firstDelivery = new DeliveryAttempt("frame-9", 1, new DateTime(2026, 9, 19, 8, 0, 0, DateTimeKind.Utc));
        var retry = new DeliveryAttempt("frame-9", 4, new DateTime(2026, 9, 19, 11, 30, 0, DateTimeKind.Utc));

        var decodedFirst = RawBlockDecoder.Decode(Layout(LayoutA()), 3, Bytes(FixtureA));
        var decodedRetry = RawBlockDecoder.Decode(Layout(LayoutA()), 3, Bytes(FixtureA));

        var identityFirst = SourceEventIdentity.Derive(Governance, 3, decodedFirst, identityFields);
        var identityRetry = SourceEventIdentity.Derive(Governance, 3, decodedRetry, identityFields);

        Assert.True(identityFirst.IsAccepted, identityFirst.Refusal?.Detail);
        Assert.Equal(identityFirst.Value!.Value, identityRetry.Value!.Value);

        // Nothing about the delivery is in the identity document.
        Assert.DoesNotContain(firstDelivery.TransportKey, identityFirst.Value.CanonicalDocument, StringComparison.Ordinal);
        Assert.DoesNotContain(retry.AttemptNumber.ToString(CultureInfo.InvariantCulture) + "}",
            identityFirst.Value.CanonicalDocument, StringComparison.Ordinal);
        Assert.DoesNotContain("2026-09-19", identityFirst.Value.CanonicalDocument, StringComparison.Ordinal);

        // A different layout revision is a different decoding contract, so it is a
        // different occurrence identity even for identical bytes.
        var otherRevision = SourceEventIdentity.Derive(Governance, 4, decodedFirst, identityFields);
        Assert.NotEqual(identityFirst.Value.Value, otherRevision.Value!.Value);

        // Different content under the same layout is a different occurrence.
        var changed = Bytes(FixtureA.Replace("000004d2", "000004d3"));
        var identityChanged = SourceEventIdentity.Derive(
            Governance, 3, RawBlockDecoder.Decode(Layout(LayoutA()), 3, changed), identityFields);
        Assert.NotEqual(identityFirst.Value.Value, identityChanged.Value!.Value);
    }

    [Fact]
    public void Identity_is_the_declared_occurrence_and_content_integrity_is_a_separate_answer()
    {
        var identityFields = new[] { Counter };

        var first = RawBlockDecoder.Decode(Layout(LayoutA()), 3, Bytes(FixtureA));

        // Same declared occurrence, different measurement: ONE identity, two contents.
        // The downstream acceptance authority must be able to see that as a conflicting
        // delivery, so the decoder must not paper over it by hashing the whole payload
        // into the identity.
        var sameOccurrenceOtherValue = RawBlockDecoder.Decode(
            Layout(LayoutA()), 3, Bytes(FixtureA.Replace("000048c1", "0000c841")));

        var identityOne = SourceEventIdentity.Derive(Governance, 3, first, identityFields);
        var identityTwo = SourceEventIdentity.Derive(Governance, 3, sameOccurrenceOtherValue, identityFields);

        Assert.Equal(identityOne.Value!.Value, identityTwo.Value!.Value);
        Assert.NotEqual(first.ContentDigest, sameOccurrenceOtherValue.ContentDigest);
        Assert.NotEqual(first.PayloadHash, sameOccurrenceOtherValue.PayloadHash);

        // Two legitimate events whose measurements happen to be identical stay distinct
        // when their declared sequence differs.
        var laterOccurrence = RawBlockDecoder.Decode(
            Layout(LayoutA()), 3, Bytes(FixtureA.Replace("000004d2", "000004d3")));
        var identityLater = SourceEventIdentity.Derive(Governance, 3, laterOccurrence, identityFields);
        Assert.NotEqual(identityOne.Value.Value, identityLater.Value!.Value);

        // A retry of the very same delivery is the same occurrence and the same content.
        var replay = RawBlockDecoder.Decode(Layout(LayoutA()), 3, Bytes(FixtureA));
        Assert.Equal(identityOne.Value.Value, SourceEventIdentity.Derive(Governance, 3, replay, identityFields).Value!.Value);
        Assert.Equal(first.ContentDigest, replay.ContentDigest);
    }

    [Fact]
    public void Identity_member_order_and_type_are_canonical()
    {
        var decoded = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA));

        // The declared order of the members must not change the identity.
        var one = SourceEventIdentity.Derive(Governance, 1, decoded, new[] { Counter, Tag });
        var other = SourceEventIdentity.Derive(Governance, 1, decoded, new[] { Tag, Counter });
        Assert.Equal(one.Value!.Value, other.Value!.Value);
        Assert.Equal(one.Value.CanonicalDocument, other.Value.CanonicalDocument);

        // The same textual value under a different declared type is a different member,
        // so the document carries the type beside the value.
        Assert.Contains("\"type\":\"uint32\"", one.Value.CanonicalDocument);
        Assert.Contains("\"type\":\"string\"", one.Value.CanonicalDocument);

        // A duplicated identity member cannot inflate the document.
        var duplicated = SourceEventIdentity.Derive(Governance, 1, decoded, new[] { Counter, Counter });
        Assert.Equal(2, duplicated.Value!.CanonicalDocument.Split("\"fieldId\"").Length - 1);
    }

    [Fact]
    public void A_typed_source_item_is_never_decoded_from_raw_bytes()
    {
        var layout = RawLayoutKernel.Normalize(Layout(LayoutA())).Value!;

        var allRaw = new Dictionary<Guid, AcquisitionFieldFact>();
        foreach (var member in layout.Members)
        {
            allRaw[member.FieldId] = new AcquisitionFieldFact(member.FieldId, 1, member.MemberType, SourceLocatorGrammar.RawMember);
        }

        Assert.Null(TypedValueGuard.Check(layout.Members, allRaw));

        // One member now reads a typed OPC node. Decoding it from the block would be a
        // second reading of the same field that could disagree with the provider's.
        var mixed = new Dictionary<Guid, AcquisitionFieldFact>(allRaw)
        {
            [Temperature] = new(Temperature, 1, "float32", SourceLocatorGrammar.OpcNode)
        };
        var refusal = TypedValueGuard.Check(layout.Members, mixed);
        Assert.NotNull(refusal);
        Assert.Equal(DecodeCodes.TypedValueNotRawDecoded, refusal!.Code);
        Assert.Contains(Temperature.ToString("D"), refusal.Detail);

        // A member the dataset does not govern at all is refused as a layout fault.
        var missing = new Dictionary<Guid, AcquisitionFieldFact>(allRaw);
        missing.Remove(Tag);
        Assert.Equal(DecodeCodes.LayoutInvalid, TypedValueGuard.Check(layout.Members, missing)!.Code);
    }

    [Fact]
    public void An_identity_that_the_layout_does_not_place_is_refused()
    {
        var decoded = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA));

        var missing = SourceEventIdentity.Derive(Governance, 1, decoded, new[] { Energy });
        Assert.False(missing.IsAccepted);
        Assert.Equal(DecodeCodes.EventIdentityMissing, missing.Refusal!.Code);

        var none = SourceEventIdentity.Derive(Governance, 1, decoded, Array.Empty<Guid>());
        Assert.False(none.IsAccepted);
        Assert.Equal(DecodeCodes.EventIdentityMissing, none.Refusal!.Code);

        var refusedDecode = RawBlockDecoder.Decode(Layout(LayoutA()), 1, Bytes(FixtureA).AsSpan(0, 4));
        var fromRefusal = SourceEventIdentity.Derive(Governance, 1, refusedDecode, new[] { Counter });
        Assert.False(fromRefusal.IsAccepted);
        Assert.Equal(DecodeCodes.EventIdentityInvalid, fromRefusal.Refusal!.Code);
    }
}
