# GenerateProjectDocumentation.ps1
# Purpose:
# Generate one full TXT documentation file containing:
# - Project/folder structure numbering
# - Every .cs file path
# - Full source code content of every .cs file
#
# Expected location:
# C:\Workspace\PlantProcess-IQ\tools\GenerateProjectDocumentation.ps1
#
# It automatically uses the parent folder as project root:
# C:\Workspace\PlantProcess-IQ

param(
    [string]$RootPath,
    [string]$OutputFolder
)

# -----------------------------
# 1. Resolve project root
# -----------------------------

$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path

if ([string]::IsNullOrWhiteSpace($RootPath)) {
    $RootPath = Split-Path -Parent $scriptDirectory
}

if (-not (Test-Path $RootPath)) {
    throw "Root path does not exist: $RootPath"
}

# -----------------------------
# 2. Resolve output folder
# -----------------------------

if ([string]::IsNullOrWhiteSpace($OutputFolder)) {
    $OutputFolder = $scriptDirectory
}

if (-not (Test-Path $OutputFolder)) {
    New-Item -ItemType Directory -Path $OutputFolder | Out-Null
}

# -----------------------------
# 3. Build output file name
# -----------------------------

$projectFolderName = Split-Path $RootPath -Leaf

# Example: PlantProcess-IQ -> PlantProcessIQ
$cleanProjectName = ($projectFolderName -replace '[^a-zA-Z0-9]', '')

$generationDate = Get-Date -Format "ddMMMyyyy"

$outputFileName = "${cleanProjectName}_${generationDate}.txt"
$outputFilePath = Join-Path $OutputFolder $outputFileName

# -----------------------------
# 4. Excluded folders
# -----------------------------

$excludedFolders = @(
    ".git",
    ".github",
    ".vs",
    "bin",
    "obj",
    "node_modules",
    "packages",
    ".idea"
)

function Test-IsExcludedPath {
    param(
        [string]$Path
    )

    foreach ($excludedFolder in $excludedFolders) {
        if ($Path -match "\\$([regex]::Escape($excludedFolder))(\\|$)") {
            return $true
        }
    }

    return $false
}

# -----------------------------
# 5. Get .cs files
# -----------------------------

$csFiles = Get-ChildItem -Path $RootPath -Recurse -File -Filter "*.cs" |
    Where-Object { -not (Test-IsExcludedPath $_.FullName) } |
    Sort-Object FullName

# -----------------------------
# 6. Prepare StringBuilder
# -----------------------------

$builder = New-Object System.Text.StringBuilder

function Add-Line {
    param([string]$Text = "")
    [void]$builder.AppendLine($Text)
}

# -----------------------------
# 7. File header
# -----------------------------

Add-Line "================================================================================"
Add-Line "PROJECT SOURCE DOCUMENTATION"
Add-Line "================================================================================"
Add-Line "Project Name      : $projectFolderName"
Add-Line "Project Root Path : $RootPath"
Add-Line "Generated At      : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Add-Line "Generated By      : GenerateProjectDocumentation.ps1"
Add-Line "Total .cs Files   : $($csFiles.Count)"
Add-Line "Output File       : $outputFilePath"
Add-Line "================================================================================"
Add-Line ""

# -----------------------------
# 8. Build numbered structure
# -----------------------------

Add-Line "PROJECT STRUCTURE"
Add-Line "================================================================================"
Add-Line ""

$indexMap = @{}

foreach ($file in $csFiles) {

    $relativePath = $file.FullName.Substring($RootPath.Length).TrimStart("\")
    $parts = $relativePath -split "\\"

    $currentKey = ""
    $numberPrefix = ""

    for ($i = 0; $i -lt $parts.Length; $i++) {

        $part = $parts[$i]

        if ([string]::IsNullOrWhiteSpace($currentKey)) {
            $currentKey = $part
        }
        else {
            $currentKey = "$currentKey\$part"
        }

        if (-not $indexMap.ContainsKey($currentKey)) {

            if ($i -eq 0) {
                $sameLevelExisting = $indexMap.Keys |
                    Where-Object { ($_ -split "\\").Count -eq 1 }

                $newNumber = $sameLevelExisting.Count + 1
                $indexMap[$currentKey] = "$newNumber"
            }
            else {
                $parentKey = ($parts[0..($i - 1)] -join "\")
                $parentNumber = $indexMap[$parentKey]

                $sameLevelExisting = $indexMap.Keys |
                    Where-Object {
                        ($_ -like "$parentKey\*") -and
                        (($_ -split "\\").Count -eq ($i + 1))
                    }

                $newNumber = $sameLevelExisting.Count + 1
                $indexMap[$currentKey] = "$parentNumber.$newNumber"
            }

            $indent = "    " * $i
            Add-Line "$indent$($indexMap[$currentKey]). $part"
        }
    }
}

Add-Line ""
Add-Line ""

# -----------------------------
# 9. Add full file contents
# -----------------------------

Add-Line "SOURCE CODE FILES"
Add-Line "================================================================================"
Add-Line ""

$fileCounter = 1

foreach ($file in $csFiles) {

    $relativePath = $file.FullName.Substring($RootPath.Length).TrimStart("\")
    $structureNumber = $indexMap[$relativePath]

    Add-Line "================================================================================"
    Add-Line "$structureNumber. $($file.Name)"
    Add-Line "Path: $($file.FullName)"
    Add-Line "Relative Path: $relativePath"
    Add-Line "Size: $($file.Length) bytes"
    Add-Line "Last Modified: $($file.LastWriteTime.ToString('yyyy-MM-dd HH:mm:ss'))"
    Add-Line "================================================================================"
    Add-Line ""

    try {
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        Add-Line $content
    }
    catch {
        Add-Line "ERROR: Could not read file content."
        Add-Line "Reason: $($_.Exception.Message)"
    }

    Add-Line ""
    Add-Line ""
    $fileCounter++
}

# -----------------------------
# 10. Write output as UTF-8
# -----------------------------

[System.IO.File]::WriteAllText(
    $outputFilePath,
    $builder.ToString(),
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host ""
Write-Host "Documentation generated successfully." -ForegroundColor Green
Write-Host "Output file:" -ForegroundColor Cyan
Write-Host $outputFilePath
Write-Host ""