using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Npgsql;
using NpgsqlTypes;

namespace PlantProcess.Infrastructure.Bulk;

public interface ITelemetryBulkRepository
{
    Task BulkInsertAsync(
        IReadOnlyList<ParameterObservationInsertRow> batch,
        CancellationToken cancellationToken);
}

/// <summary>
/// High-performance PostgreSQL COPY-based repository for parameter observations.
/// 
/// Important:
/// - This class bypasses EF Core intentionally for high-volume telemetry ingestion.
/// - Column names must match the real PostgreSQL snake_case table generated by EF Core.
/// - This repository must stay aligned with ParameterObservationInsertRow and the
///   parameter_observations table.
/// </summary>
public sealed class TelemetryBulkRepository : ITelemetryBulkRepository
{
    private readonly string _connectionString;
    private readonly ILogger<TelemetryBulkRepository> _logger;

    public TelemetryBulkRepository(
        IConfiguration configuration,
        ILogger<TelemetryBulkRepository> logger)
    {
        _connectionString =
            configuration.GetConnectionString("PlantProcessDb")
            ?? throw new InvalidOperationException("Connection string 'PlantProcessDb' is missing.");

        _logger = logger;
    }

    public async Task BulkInsertAsync(
        IReadOnlyList<ParameterObservationInsertRow> batch,
        CancellationToken cancellationToken)
    {
        if (batch.Count == 0)
        {
            _logger.LogDebug("Telemetry bulk insert skipped because batch is empty.");
            return;
        }

        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);

        const string copyCommand = """
            COPY parameter_observations
            (
                id,
                created_at_utc,
                updated_at_utc,
                is_synthetic,
                source_system,
                source_record_id,
                is_deleted,
                deleted_at_utc,
                deleted_reason,
                material_unit_id,
                process_step_execution_id,
                parameter_definition_id,
                equipment_id,
                observed_at_utc,
                observed_at_local,
                plant_time_zone_id,
                plant_utc_offset_minutes,
                numeric_value,
                text_value,
                boolean_value,
                unit_of_measure,
                quality_flag,
                raw_value
            )
            FROM STDIN (FORMAT BINARY)
            """;

        _logger.LogInformation(
            "Starting telemetry bulk insert. Rows={Rows}",
            batch.Count);

        await using var writer = await connection.BeginBinaryImportAsync(
            copyCommand,
            cancellationToken);

        foreach (var row in batch)
        {
            await writer.StartRowAsync(cancellationToken);

            await writer.WriteAsync(row.Id, NpgsqlDbType.Uuid, cancellationToken);
            await writer.WriteAsync(EnsureUtc(row.CreatedAtUtc), NpgsqlDbType.TimestampTz, cancellationToken);
            await WriteNullableTimestampTzAsync(writer, row.UpdatedAtUtc, cancellationToken);

            await writer.WriteAsync(row.IsSynthetic, NpgsqlDbType.Boolean, cancellationToken);
            await WriteNullableTextAsync(writer, row.SourceSystem, cancellationToken);
            await WriteNullableTextAsync(writer, row.SourceRecordId, cancellationToken);

            await writer.WriteAsync(row.IsDeleted, NpgsqlDbType.Boolean, cancellationToken);
            await WriteNullableTimestampTzAsync(writer, row.DeletedAtUtc, cancellationToken);
            await WriteNullableTextAsync(writer, row.DeletedReason, cancellationToken);

            await writer.WriteAsync(row.MaterialUnitId, NpgsqlDbType.Uuid, cancellationToken);
            await WriteNullableUuidAsync(writer, row.ProcessStepExecutionId, cancellationToken);
            await writer.WriteAsync(row.ParameterDefinitionId, NpgsqlDbType.Uuid, cancellationToken);
            await WriteNullableUuidAsync(writer, row.EquipmentId, cancellationToken);

            await writer.WriteAsync(EnsureUtc(row.ObservedAtUtc), NpgsqlDbType.TimestampTz, cancellationToken);
            await writer.WriteAsync(
                DateTime.SpecifyKind(row.ObservedAtLocal, DateTimeKind.Unspecified),
                NpgsqlDbType.Timestamp,
                cancellationToken);

            await writer.WriteAsync(
                string.IsNullOrWhiteSpace(row.PlantTimeZoneId)
                    ? "UTC"
                    : row.PlantTimeZoneId.Trim(),
                NpgsqlDbType.Text,
                cancellationToken);

            await writer.WriteAsync(row.PlantUtcOffsetMinutes, NpgsqlDbType.Integer, cancellationToken);

            await WriteNullableDecimalAsync(writer, row.NumericValue, cancellationToken);
            await WriteNullableTextAsync(writer, row.TextValue, cancellationToken);
            await WriteNullableBooleanAsync(writer, row.BooleanValue, cancellationToken);
            await WriteNullableTextAsync(writer, row.UnitOfMeasure, cancellationToken);

            await writer.WriteAsync(
                string.IsNullOrWhiteSpace(row.QualityFlag)
                    ? "Valid"
                    : row.QualityFlag.Trim(),
                NpgsqlDbType.Text,
                cancellationToken);

            await WriteNullableTextAsync(writer, row.RawValue, cancellationToken);
        }

        var inserted = await writer.CompleteAsync(cancellationToken);

        _logger.LogInformation(
            "Telemetry bulk insert completed. RowsInserted={RowsInserted}",
            inserted);
    }

    private static DateTime EnsureUtc(DateTime value)
    {
        return value.Kind switch
        {
            DateTimeKind.Utc => value,
            DateTimeKind.Local => value.ToUniversalTime(),
            _ => DateTime.SpecifyKind(value, DateTimeKind.Utc)
        };
    }

    private static async Task WriteNullableTextAsync(
        NpgsqlBinaryImporter writer,
        string? value,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            await writer.WriteNullAsync(cancellationToken);
            return;
        }

        await writer.WriteAsync(value.Trim(), NpgsqlDbType.Text, cancellationToken);
    }

    private static async Task WriteNullableUuidAsync(
        NpgsqlBinaryImporter writer,
        Guid? value,
        CancellationToken cancellationToken)
    {
        if (!value.HasValue)
        {
            await writer.WriteNullAsync(cancellationToken);
            return;
        }

        await writer.WriteAsync(value.Value, NpgsqlDbType.Uuid, cancellationToken);
    }

    private static async Task WriteNullableTimestampTzAsync(
        NpgsqlBinaryImporter writer,
        DateTime? value,
        CancellationToken cancellationToken)
    {
        if (!value.HasValue)
        {
            await writer.WriteNullAsync(cancellationToken);
            return;
        }

        await writer.WriteAsync(EnsureUtc(value.Value), NpgsqlDbType.TimestampTz, cancellationToken);
    }

    private static async Task WriteNullableDecimalAsync(
        NpgsqlBinaryImporter writer,
        decimal? value,
        CancellationToken cancellationToken)
    {
        if (!value.HasValue)
        {
            await writer.WriteNullAsync(cancellationToken);
            return;
        }

        await writer.WriteAsync(value.Value, NpgsqlDbType.Numeric, cancellationToken);
    }

    private static async Task WriteNullableBooleanAsync(
        NpgsqlBinaryImporter writer,
        bool? value,
        CancellationToken cancellationToken)
    {
        if (!value.HasValue)
        {
            await writer.WriteNullAsync(cancellationToken);
            return;
        }

        await writer.WriteAsync(value.Value, NpgsqlDbType.Boolean, cancellationToken);
    }
}