using System.Globalization;
using System.Text;

namespace PlantProcess.Application.Reporting;

/// <summary>
/// Shared deterministic PDF writer for customer-facing reports.
/// It paints the #F4F6F8 report surface, a Deep-Navy brand header, and a maintained footer.
/// The embedded markers are intentionally testable in the generated bytes.
/// </summary>
public static class BrandedPdfWriter
{
    private const string LightSurfaceMarker = "PPIQ-LIGHT-SURFACE:#F4F6F8";
    private const string HeaderMarker = "PPIQ-BRAND-HEADER";
    private const string FooterMarker = "PPIQ-BRAND-FOOTER";

    public static byte[] Create(string title, IEnumerable<string> sourceLines)
    {
        var lines = sourceLines
            .Select(Sanitize)
            .SelectMany(line => Wrap(line, 92))
            .Take(900)
            .ToList();
        if (lines.Count == 0) lines.Add("No report content.");

        var pages = lines.Chunk(45).Select(chunk => chunk.ToArray()).ToArray();
        var objects = new List<string>();
        var pageObjectNumbers = new List<int>();
        var contentObjectNumbers = new List<int>();

        objects.Add("<< /Type /Catalog /Pages 2 0 R >>");
        objects.Add(""); // pages object filled after page objects are allocated
        objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
        objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

        for (var index = 0; index < pages.Length; index++)
        {
            var pageObject = objects.Count + 1;
            var contentObject = pageObject + 1;
            pageObjectNumbers.Add(pageObject);
            contentObjectNumbers.Add(contentObject);
            objects.Add($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents {contentObject} 0 R >>");
            var content = BuildPage(title, pages[index], index + 1, pages.Length);
            objects.Add($"<< /Length {Encoding.ASCII.GetByteCount(content)} >>\nstream\n{content}\nendstream");
        }

        objects[1] = $"<< /Type /Pages /Kids [{string.Join(" ", pageObjectNumbers.Select(n => $"{n} 0 R"))}] /Count {pages.Length} >>";

        var output = new StringBuilder();
        output.AppendLine("%PDF-1.4");
        output.AppendLine($"% {LightSurfaceMarker} {HeaderMarker} {FooterMarker}");
        var offsets = new List<int> { 0 };
        for (var i = 0; i < objects.Count; i++)
        {
            offsets.Add(Encoding.ASCII.GetByteCount(output.ToString()));
            output.AppendLine($"{i + 1} 0 obj");
            output.AppendLine(objects[i]);
            output.AppendLine("endobj");
        }
        var xref = Encoding.ASCII.GetByteCount(output.ToString());
        output.AppendLine("xref");
        output.AppendLine($"0 {objects.Count + 1}");
        output.AppendLine("0000000000 65535 f ");
        foreach (var offset in offsets.Skip(1)) output.AppendLine($"{offset:0000000000} 00000 n ");
        output.AppendLine($"trailer << /Size {objects.Count + 1} /Root 1 0 R /Info << /Title ({Escape(title)}) /Subject ({LightSurfaceMarker}; {HeaderMarker}; {FooterMarker}) >> >>");
        output.AppendLine("startxref");
        output.AppendLine(xref.ToString(CultureInfo.InvariantCulture));
        output.AppendLine("%%EOF");
        return Encoding.ASCII.GetBytes(output.ToString());
    }

    private static string BuildPage(string title, IReadOnlyList<string> lines, int page, int total)
    {
        var content = new StringBuilder();
        // #F4F6F8 light report surface: 244/246/248.
        content.AppendLine("0.9569 0.9647 0.9725 rg 0 0 595 842 re f");
        // #050B18 brand header.
        content.AppendLine("0.0196 0.0431 0.0941 rg 0 770 595 72 re f");
        content.AppendLine("BT /F2 17 Tf 1 1 1 rg 42 808 Td (PlantProcess IQ / SOU) Tj ET");
        content.AppendLine($"BT /F1 10 Tf 0.8 0.9 1 rg 42 786 Td ({Escape(title)}) Tj ET");
        content.AppendLine("0.0392 0.5176 1 rg 42 760 511 2 re f");
        content.AppendLine("BT /F1 10 Tf 0.08 0.13 0.20 rg 42 738 Td");
        foreach (var line in lines)
        {
            content.AppendLine($"({Escape(line)}) Tj");
            content.AppendLine("0 -14 Td");
        }
        content.AppendLine("ET");
        content.AppendLine("0.0627 0.1647 0.2627 rg 0 0 595 34 re f");
        content.AppendLine($"BT /F1 8 Tf 0.92 0.96 1 rg 42 13 Td (Connect Your Plant Data. Understand Your Process.  |  Page {page}/{total}) Tj ET");
        return content.ToString();
    }

    private static IEnumerable<string> Wrap(string line, int width)
    {
        if (string.IsNullOrWhiteSpace(line)) { yield return " "; yield break; }
        var remaining = line.Trim();
        while (remaining.Length > width)
        {
            var cut = remaining.LastIndexOf(' ', width);
            if (cut < width / 2) cut = width;
            yield return remaining[..cut];
            remaining = remaining[cut..].TrimStart();
        }
        yield return remaining;
    }

    private static string Sanitize(string value) => value
        .Replace("\u2013", "-")
        .Replace("\u2014", "-")
        .Replace("\u2192", "->")
        .Replace("\u20ac", "EUR")
        .Replace("\u2264", "<=")
        .Replace("\u2265", ">=");

    private static string Escape(string value) => Sanitize(value)
        .Replace("\\", "\\\\")
        .Replace("(", "\\(")
        .Replace(")", "\\)");
}