// @vitest-environment node
// PPIQ T-040 AUTH-02. THE FRONTEND BOOTSTRAP CREDENTIAL, GUARDED.
//
// This product has no login page yet. AuthContext bootstraps by trying a
// refresh cookie and, when there is none, logging in with the VITE_SMOKE_
// values Vite compiled into the bundle from Frontend/PlantProcess.Web/.env.local
// - and that file is generated by scripts/env/use-profile.ps1 on every run of
// start-web.ps1.
//
// The defect this guards against, measured on 08-Aug: the generator wrote a
// hardcoded placeholder for the password while interpolating the user name from
// the loaded profile. A browser holding a refresh cookie never reaches the
// password path, so the failure was invisible in daily use and appeared only in
// a clean context - Playwright, an incognito window, a customer laptop.
//
// THIS TEST READS THE GENERATOR, NEVER A CREDENTIAL. use-profile.ps1 contains an
// interpolation, not a value, so nothing secret can pass through here and
// nothing secret can be printed by a failure message.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(process.cwd(), "..", "..");
const GENERATOR = join(REPO_ROOT, "scripts", "env", "use-profile.ps1");
const GITIGNORE = join(REPO_ROOT, ".gitignore");
const AUTH_CONTEXT = join(process.cwd(), "src", "state", "AuthContext.tsx");

const generator = () => readFileSync(GENERATOR, "utf8");

describe("the frontend bootstrap credential comes from the profile, never from a literal", () => {
  it("interpolates the smoke password into the generated env file", () => {
    const hits = generator().split("VITE_SMOKE_PASSWORD=$env:VITE_SMOKE_PASSWORD").length - 1;
    expect(hits, "use-profile.ps1 must write the loaded profile value, not a constant").toBe(1);
  });

  it("assigns no literal to the smoke password anywhere in the generator", () => {
    const offenders = generator()
      .split("\n")
      .map((line, index) => ({ line: line.trim(), number: index + 1 }))
      .filter((row) => row.line.startsWith("VITE_SMOKE_PASSWORD="))
      .filter((row) => !row.line.startsWith("VITE_SMOKE_PASSWORD=$env:"));
    expect(offenders.map((row) => row.number), "a literal password reinstates the clean-browser defect").toEqual([]);
  });

  it("does not carry the retired placeholder", () => {
    const marker = ["change", "me", "before", "production"].join("-");
    expect(generator().includes(marker), "the retired placeholder must not return").toBe(false);
  });

  it("interpolates the smoke user name too, so both halves come from one source", () => {
    const hits = generator().split("VITE_SMOKE_USERNAME=$env:VITE_SMOKE_USERNAME").length - 1;
    expect(hits).toBe(1);
  });

  it("keeps the generated env file out of version control", () => {
    const ignored = readFileSync(GITIGNORE, "utf8");
    expect(ignored.includes("Frontend/PlantProcess.Web/.env.local") || ignored.includes(".env.local")).toBe(true);
  });

  it("is guarding a contract the application actually depends on", () => {
    const context = readFileSync(AUTH_CONTEXT, "utf8");
    expect(context.includes("VITE_SMOKE_USERNAME")).toBe(true);
    expect(context.includes("VITE_SMOKE_PASSWORD")).toBe(true);
  });

  it("keeps the presentation profile reachable from both start scripts", () => {
    const web = readFileSync(join(REPO_ROOT, "scripts", "run", "start-web.ps1"), "utf8");
    const api = readFileSync(join(REPO_ROOT, "scripts", "run", "start-api.ps1"), "utf8");
    const accepts = (text: string) => /ValidateSet\([^)]*"presentation"/.test(text);
    expect(accepts(web), "start-web.ps1 must accept -Profile presentation").toBe(true);
    expect(accepts(api), "start-api.ps1 must accept -Profile presentation").toBe(true);
  });
});